#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSociety
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HumaneSocietyDB")]
	public partial class HsdbLinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdopter(Adopter instance);
    partial void UpdateAdopter(Adopter instance);
    partial void DeleteAdopter(Adopter instance);
    partial void InsertAnimal(Animal instance);
    partial void UpdateAnimal(Animal instance);
    partial void DeleteAnimal(Animal instance);
    #endregion
		
		public HsdbLinqToSqlDataContext() : 
				base(global::HumaneSociety.Properties.Settings.Default.HumaneSocietyDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HsdbLinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HsdbLinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HsdbLinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HsdbLinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Adopter> Adopters
		{
			get
			{
				return this.GetTable<Adopter>();
			}
		}
		
		public System.Data.Linq.Table<Animal> Animals
		{
			get
			{
				return this.GetTable<Animal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adopter")]
	public partial class Adopter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PersonID;
		
		private string _P_FirstName;
		
		private string _P_LastName;
		
		private string _P_Address;
		
		private string _P_City;
		
		private string _P_State;
		
		private string _P_Zip;
		
		private string _P_Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersonIDChanging(int value);
    partial void OnPersonIDChanged();
    partial void OnP_FirstNameChanging(string value);
    partial void OnP_FirstNameChanged();
    partial void OnP_LastNameChanging(string value);
    partial void OnP_LastNameChanged();
    partial void OnP_AddressChanging(string value);
    partial void OnP_AddressChanged();
    partial void OnP_CityChanging(string value);
    partial void OnP_CityChanged();
    partial void OnP_StateChanging(string value);
    partial void OnP_StateChanged();
    partial void OnP_ZipChanging(string value);
    partial void OnP_ZipChanged();
    partial void OnP_PhoneChanging(string value);
    partial void OnP_PhoneChanged();
    #endregion
		
		public Adopter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PersonID
		{
			get
			{
				return this._PersonID;
			}
			set
			{
				if ((this._PersonID != value))
				{
					this.OnPersonIDChanging(value);
					this.SendPropertyChanging();
					this._PersonID = value;
					this.SendPropertyChanged("PersonID");
					this.OnPersonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_FirstName", DbType="VarChar(255)")]
		public string P_FirstName
		{
			get
			{
				return this._P_FirstName;
			}
			set
			{
				if ((this._P_FirstName != value))
				{
					this.OnP_FirstNameChanging(value);
					this.SendPropertyChanging();
					this._P_FirstName = value;
					this.SendPropertyChanged("P_FirstName");
					this.OnP_FirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_LastName", DbType="VarChar(255)")]
		public string P_LastName
		{
			get
			{
				return this._P_LastName;
			}
			set
			{
				if ((this._P_LastName != value))
				{
					this.OnP_LastNameChanging(value);
					this.SendPropertyChanging();
					this._P_LastName = value;
					this.SendPropertyChanged("P_LastName");
					this.OnP_LastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Address", DbType="VarChar(255)")]
		public string P_Address
		{
			get
			{
				return this._P_Address;
			}
			set
			{
				if ((this._P_Address != value))
				{
					this.OnP_AddressChanging(value);
					this.SendPropertyChanging();
					this._P_Address = value;
					this.SendPropertyChanged("P_Address");
					this.OnP_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_City", DbType="VarChar(255)")]
		public string P_City
		{
			get
			{
				return this._P_City;
			}
			set
			{
				if ((this._P_City != value))
				{
					this.OnP_CityChanging(value);
					this.SendPropertyChanging();
					this._P_City = value;
					this.SendPropertyChanged("P_City");
					this.OnP_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_State", DbType="VarChar(10)")]
		public string P_State
		{
			get
			{
				return this._P_State;
			}
			set
			{
				if ((this._P_State != value))
				{
					this.OnP_StateChanging(value);
					this.SendPropertyChanging();
					this._P_State = value;
					this.SendPropertyChanged("P_State");
					this.OnP_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Zip", DbType="VarChar(10)")]
		public string P_Zip
		{
			get
			{
				return this._P_Zip;
			}
			set
			{
				if ((this._P_Zip != value))
				{
					this.OnP_ZipChanging(value);
					this.SendPropertyChanging();
					this._P_Zip = value;
					this.SendPropertyChanged("P_Zip");
					this.OnP_ZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Phone", DbType="VarChar(10)")]
		public string P_Phone
		{
			get
			{
				return this._P_Phone;
			}
			set
			{
				if ((this._P_Phone != value))
				{
					this.OnP_PhoneChanging(value);
					this.SendPropertyChanging();
					this._P_Phone = value;
					this.SendPropertyChanged("P_Phone");
					this.OnP_PhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Animal")]
	public partial class Animal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Room;
		
		private string _Name;
		
		private string _AnimalType;
		
		private string _Gender;
		
		private string _Food;
		
		private string _Shot;
		
		private System.Nullable<decimal> _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoomChanging(string value);
    partial void OnRoomChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAnimalTypeChanging(string value);
    partial void OnAnimalTypeChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnFoodChanging(string value);
    partial void OnFoodChanged();
    partial void OnShotChanging(string value);
    partial void OnShotChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    #endregion
		
		public Animal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Room
		{
			get
			{
				return this._Room;
			}
			set
			{
				if ((this._Room != value))
				{
					this.OnRoomChanging(value);
					this.SendPropertyChanging();
					this._Room = value;
					this.SendPropertyChanged("Room");
					this.OnRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnimalType", DbType="VarChar(255)")]
		public string AnimalType
		{
			get
			{
				return this._AnimalType;
			}
			set
			{
				if ((this._AnimalType != value))
				{
					this.OnAnimalTypeChanging(value);
					this.SendPropertyChanging();
					this._AnimalType = value;
					this.SendPropertyChanged("AnimalType");
					this.OnAnimalTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(255)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food", DbType="VarChar(255)")]
		public string Food
		{
			get
			{
				return this._Food;
			}
			set
			{
				if ((this._Food != value))
				{
					this.OnFoodChanging(value);
					this.SendPropertyChanging();
					this._Food = value;
					this.SendPropertyChanged("Food");
					this.OnFoodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shot", DbType="VarChar(255)")]
		public string Shot
		{
			get
			{
				return this._Shot;
			}
			set
			{
				if ((this._Shot != value))
				{
					this.OnShotChanging(value);
					this.SendPropertyChanging();
					this._Shot = value;
					this.SendPropertyChanged("Shot");
					this.OnShotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
